### ISSUE TITLE
the new unblocking system

### ISSUE THREAD

**Issue by cheesecat123** [uniub/uniub.github.io#2]
less of an issue more of a guide missing, there is now a numbered system instead of a url based system. please can someone add a list of which urls go to which numbers

**Comment by TJSloan08** [comment]
I've created a list that matches the URLs to the numbers.
[UniUb Lists.pdf](https://github.com/user-attachments/files/16201664/UniUb.Lists.pdf)
I will also post it on my profile.

**Comment by cheesecat123** [comment]
Thank You
]

**Comment by uniub** [comment]
Please only make issues about real problems with the site. To find which urls are linked to which numbers please go to [this ](https://github.com/uniub/uniub.github.io/blob/master/js/proxymanager.js)file under the repo
